#!/usr/bin/env bash
#
# Install this repo's git hooks. Idempotent; safe to re-run.
#
# WHY THIS SCRIPT EXISTS
# ----------------------
# `.git/hooks/` is not version-controlled, so an installed hook is invisible to
# review, to CI and to every other session. The last time hook wiring on this repo was
# left to a hand-run command it went wrong silently for a day:
# `core.hooksPath` still pointed at a pre-RENAME absolute path, git does not warn or
# fall back when that directory is missing, and ZERO hooks ran —
#   docs/issues/2026-08-30-core-hookspath-points-at-pre-rename-path.md
# This tracked script is the record of what "installed" means, and it checks for that
# exact trap before doing anything.
#
# WHAT GETS INSTALLED, AND WHY BY TWO DIFFERENT ROUTES
# ---------------------------------------------------
#   pre-commit stage        -> the pre-commit.com framework (.pre-commit-config.yaml)
#   prepare-commit-msg      -> a direct shim in .git/hooks/
#   post-index-change       -> a direct shim in .git/hooks/
#
# `post-index-change` CANNOT go through the framework: it is absent from HOOK_TYPES in
# pre-commit 4.6.2's clientlib.py, which lists ten types and not that one.
#
# `prepare-commit-msg` COULD, and deliberately does not. The framework stashes every
# unstaged change in the checkout while its hooks run — not just the committing
# session's — so each installed stage adds a window in which a peer's in-flight work
# transiently reverts to HEAD and `git status` reports it clean. That is an observed
# harm on this checkout, not a projected one; see "The read-side twin" in
#   docs/issues/2026-08-31-peer-commit-captures-another-sessions-working-tree.md
# Routing a second stage through the framework would double the number of those
# windows for every session, to buy discoverability that this script already provides.
#
# Usage:
#   scripts/install-hooks.sh            # install / repair
#   scripts/install-hooks.sh --check    # report only, change nothing

set -uo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT" || exit 1

check_only=0
[ "${1:-}" = "--check" ] && check_only=1

fail=0

# ---------------------------------------------------------------- the hooksPath trap
hooks_path="$(git config --get core.hooksPath 2>/dev/null)"
if [ -n "$hooks_path" ]; then
    echo "REFUSING: core.hooksPath is set to:" >&2
    echo "    $hooks_path" >&2
    echo >&2
    echo "It overrides .git/hooks/ unconditionally, so anything installed there is" >&2
    echo "dead on arrival — and git does NOT warn when it names a missing directory." >&2
    echo "That failure is silent by design and cost this repo a day already." >&2
    echo >&2
    echo "    git config --unset core.hooksPath" >&2
    echo >&2
    echo "Then re-run this script. Verify with 'git config --get core.hooksPath'" >&2
    echo "returning nothing — an --unset that was recorded but never run is exactly" >&2
    echo "how the original bug survived being marked fixed." >&2
    exit 1
fi

git_dir="$(git rev-parse --git-dir 2>/dev/null)"
if [ -z "$git_dir" ]; then
    echo "REFUSING: not inside a git repository." >&2
    exit 1
fi

# ------------------------------------------------------- the pre-commit.com framework
if command -v pre-commit >/dev/null 2>&1; then
    if [ "$check_only" = "1" ]; then
        if [ -f "$git_dir/hooks/pre-commit" ] &&
            grep -q 'generated by pre-commit' "$git_dir/hooks/pre-commit" 2>/dev/null; then
            echo "ok      pre-commit stage      framework shim present"
        else
            echo "MISSING pre-commit stage      run without --check"
            fail=1
        fi
    else
        pre-commit install >/dev/null || {
            echo "REFUSING: 'pre-commit install' failed." >&2
            exit 1
        }
        echo "ok      pre-commit stage      installed"
    fi
else
    echo "MISSING pre-commit is not on PATH — install it (pipx install pre-commit)" >&2
    fail=1
fi

# ------------------------------------------------------------------- the direct shims
install_shim() {
    hook_name="$1"
    target="$2"
    dest="$git_dir/hooks/$hook_name"

    if [ ! -x "$PROJECT_ROOT/$target" ]; then
        echo "MISSING $hook_name — $target is not executable" >&2
        fail=1
        return
    fi

    # Never clobber a framework-generated shim; that would silently disable whatever
    # stage the framework had wired there.
    if [ -f "$dest" ] && grep -q 'generated by pre-commit' "$dest" 2>/dev/null; then
        echo "REFUSING: $dest is a pre-commit-generated shim." >&2
        echo "Someone ran 'pre-commit install --hook-type $hook_name'. Resolve that" >&2
        echo "first — two owners for one hook file is not a state this script picks." >&2
        fail=1
        return
    fi

    if [ "$check_only" = "1" ]; then
        if [ -x "$dest" ] && grep -q "$target" "$dest" 2>/dev/null; then
            echo "ok      $hook_name      shim present"
        else
            echo "MISSING $hook_name      run without --check"
            fail=1
        fi
        return
    fi

    # The shim resolves the repo at RUN time, so it keeps working if the checkout
    # moves — which is the failure the hooksPath bug was made of.
    cat > "$dest" <<'SHIM'
#!/usr/bin/env bash
# Installed by scripts/install-hooks.sh. Thin shim: edit the tracked script, not this.
set -uo pipefail
root="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
SHIM
    printf 'exec "$root/%s" "$@"\n' "$target" >> "$dest"
    chmod +x "$dest"
    echo "ok      $hook_name      shim installed -> $target"
}

install_shim prepare-commit-msg scripts/prepare-commit-msg-session-id.sh
install_shim post-index-change scripts/post-index-change-stage-log.sh

echo
if [ "$fail" != "0" ]; then
    echo "One or more hooks are NOT installed. Nothing above is a substitute for the" >&2
    echo "positive check below." >&2
    exit 1
fi

cat <<'EOF'
Installed. Now VERIFY POSITIVELY — a successful install is compatible with the hook
never running, which is how the last hooks defect stayed invisible:

    git commit --allow-empty -m 'hook probe'
    git log -1 --format='%(trailers:key=Session-Id)'    # <- must print your session id
    git reset --hard HEAD~1                             # <- discard the probe

Several sessions share this checkout, and installing these hooks changes every
session's `git commit`. Tell them before you run this, not after.
EOF
