#!/usr/bin/env python3
"""Phase 2 by FORK -- replay a decision point through Claude Code on the subscription.

The first phase-2 route (`phase2-replay.py`) re-sent the recorded Messages API request
and billed the paid API. This route copies the session transcript up to the decision
point into a new session and resumes it with `claude -p --resume`, so the turn is
regenerated by Claude Code itself under a subscription login.

Each constraint below was PROBED on 2026-09-23, not assumed:

  - A `-p` resume refuses an empty prompt. The prompt is therefore the exact text of
    the record that followed CUT in the original (the output-style system-reminder),
    which the original also received as user-role text.
  - Injection as a hand-written `hook_additional_context` attachment reaches the model.
  - `--max-turns 1` does NOT stop a tool executing (a Read returned its file, then the
    session stopped), and a `permissions.deny` rule REMOVES the tool from the model's
    list. The only way to keep tools defined but inert is a PreToolUse deny-all hook.
  - This profile's plugin hooks inject context on resume (a SessionStart:fork
    "PROJECT BOOTSTRAP" made the first probe call `workspace`), so plugins are off.
  - A resume in another directory tells the model its cwd changed, and it stopped
    work over it. So the fork runs in the REAL checkout, under the real profile.
  - A resume re-injects any CLAUDE.md whose disk copy differs from the transcript's.
    And what the model reads is an attachment's `rendered` text, NOT `files[].content`:
    a probe that rewrote only the latter still answered from the original bytes.

Hence the design: the fork runs inside a private mount namespace (`unshare -rm`) in
which the profile's settings.json (plugins off, deny-all hook) and every CLAUDE.md /
MEMORY.md the transcript carries are bind-mounted over by files written FROM THE
TRANSCRIPT -- stripped for the s-arms. Nothing outside the namespace changes. Resume
also restores the transcript's background agents from `toolUseResult` metadata and
reports them KILLED, so that metadata (never model-visible) is dropped from the seed.

What remains different from the original, identical across arms: a resume ending on a
tool_result gets Claude Code's synthetic "Continue from where you left off." / "No
response requested." pair; plugin tools are absent; tool definitions are today's.
Arms are compared within this route only.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import pathlib
import shlex
import shutil
import subprocess
import sys
import uuid
from concurrent.futures import ThreadPoolExecutor

HERE = pathlib.Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location("replay", HERE / "phase2-replay.py")
_replay = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_replay)
ARMS = _replay.ARMS          # one registered source of arm texts, never a copy

MODEL = "claude-opus-5[1m]"  # the transcript's own model attachment at the decision point
REPO = str(HERE.parent)
PROJECT_CLAUDE_MD = REPO + "/CLAUDE.md"
PROFILE = pathlib.Path(os.environ.get("CLAUDE_CONFIG_DIR", "~/.claude-kat")).expanduser()
# The registered stripped replacement: header line plus the one-paragraph description,
# byte-identical to the block in the API route's stripped request.
STRIPPED = ("# codescout\n\nRust MCP server giving LLMs IDE-grade code intelligence — "
            "symbol-level navigation, semantic search, git integration. Inspired by "
            "[Serena](https://github.com/oraios/serena).\n")
DENY_HOOK = {"PreToolUse": [{"matcher": "*", "hooks": [{
    "type": "command",
    "command": "echo '{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\","
               "\"permissionDecision\":\"deny\",\"permissionDecisionReason\":"
               "\"replay: tool execution disabled\"}}'"}]}]}


def strip_rendered(r: dict) -> None:
    """Replace the project CLAUDE.md body inside an instructions record's `rendered`
    text -- the bytes the model actually reads -- and in `files` for consistency."""
    a = r["attachment"]
    body = next((f["content"] for f in a.get("files", []) if f.get("path") == PROJECT_CLAUDE_MD), None)
    if body is None:
        return
    for c in r.get("rendered") or []:
        n = c["content"].count(body)
        if n != 1:
            sys.exit(f"stripping: project CLAUDE.md body found {n}x in rendered text, want 1")
        c["content"] = c["content"].replace(body, STRIPPED)
    for f in a["files"]:
        if f.get("path") == PROJECT_CLAUDE_MD:
            f["content"] = STRIPPED


class Shadow:
    """Files bind-mounted over the real ones inside the fork's mount namespace."""

    def __init__(self, base: pathlib.Path, variant: str, src: list[dict]) -> None:
        self.dir = base / f"shadow-{variant}"
        self.dir.mkdir(parents=True, exist_ok=True)
        self.stripped = variant == "stripped"
        self.mounts: list[tuple[str, str]] = []
        s = json.load(open(PROFILE / "settings.json"))
        s["enabledPlugins"] = {}
        s["hooks"] = DENY_HOOK
        self._add(str(PROFILE / "settings.json"), json.dumps(s, indent=2))
        last = [r for r in src if (r.get("attachment") or {}).get("type") == "instructions"][-1]
        for f in last["attachment"]["files"]:
            p, body = f["path"], f.get("content", "")
            if p == PROJECT_CLAUDE_MD and self.stripped:
                body = STRIPPED
            if not os.path.exists(p):
                sys.exit(f"cannot shadow {p}: no file there to mount over")
            self._add(p, body)

    def _add(self, target: str, body: str) -> None:
        f = self.dir / f"{len(self.mounts)}-{pathlib.Path(target).name}"
        f.write_text(body)
        self.mounts.append((str(f), target))

    def wrap(self, argv: list[str]) -> list[str]:
        binds = " && ".join(f"mount --bind {shlex.quote(a)} {shlex.quote(b)}" for a, b in self.mounts)
        return ["unshare", "-rm", "sh", "-c", binds + ' && exec "$@"', "sh", *argv]


def seed(src: list[dict], cut: int, arm_text: str | None, stripped: bool, sid: str) -> list[dict]:
    rows = []
    for r in src[:cut + 1]:
        if r.get("type") == "queue-operation":
            continue
        if (r.get("attachment") or {}).get("type") == "queued_command":
            continue
        r = json.loads(json.dumps(r))
        # UI/task metadata, never model-visible. Left in, a resume restores the
        # transcript's async_launched agents and reports them KILLED.
        r.pop("toolUseResult", None)
        if stripped and (r.get("attachment") or {}).get("type") == "instructions":
            strip_rendered(r)
        for k in ("sessionId", "session_id"):
            if k in r:
                r[k] = sid
        rows.append(r)
    if arm_text is not None:
        last = next(r for r in reversed(rows) if r.get("uuid"))
        rec = {k: last[k] for k in ("cwd", "entrypoint", "gitBranch", "isSidechain",
                                    "userType", "version") if k in last}
        rec.update(type="attachment", uuid=str(uuid.uuid4()), parentUuid=last["uuid"],
                   sessionId=sid, timestamp=last.get("timestamp"),
                   attachment={"type": "hook_additional_context", "content": [arm_text],
                               "hookName": "PostToolUse", "toolUseID": "PostToolUse",
                               "hookEvent": "PostToolUse"})
        rows.append(rec)
    return rows


def first_turn(events: list[dict]) -> tuple[str, list[str], str | None]:
    """Blocks of the FIRST real assistant message, serialised as the API route does."""
    parts, tools, mid = [], [], None
    for e in events:
        if e.get("type") != "assistant":
            continue
        m = e["message"]
        if m.get("model") == "<synthetic>":
            continue
        if mid is None:
            mid = m.get("id")
        if m.get("id") != mid:
            break
        for b in m.get("content", []):
            if b.get("type") == "tool_use":
                tools.append(b["name"])
                parts.append(json.dumps(b.get("input", {}), ensure_ascii=False))
            elif b.get("type") == "text":
                parts.append(b["text"])
    return "\n".join(parts), tools, mid


def fork(src, cut, prompt, projdir, shadow: Shadow, mcp, arm, run, timeout, keep) -> dict:
    label = ("s" if shadow.stripped else "") + arm
    sid = str(uuid.uuid4())
    seed_path = projdir / f"{sid}.jsonl"
    with open(seed_path, "w") as fh:
        for r in seed(src, cut, ARMS.get(arm), shadow.stripped, sid):
            fh.write(json.dumps(r) + "\n")
    env = {k: v for k, v in os.environ.items()
           if k not in ("ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_BASE_URL")}
    env["CLAUDE_CONFIG_DIR"] = str(PROFILE)
    cmd = shadow.wrap(["claude", "-p", prompt, "--resume", sid, "--fork-session",
                       "--model", MODEL, "--mcp-config", mcp, "--strict-mcp-config",
                       "--max-turns", "1", "--output-format", "stream-json", "--verbose"])
    fork_sid = None
    try:
        p = subprocess.run(cmd, cwd=REPO, env=env, capture_output=True, text=True,
                           timeout=timeout, stdin=subprocess.DEVNULL)
        events = [json.loads(l) for l in p.stdout.splitlines() if l.startswith("{")]
        init = next((e for e in events if e.get("subtype") == "init"), {})
        fork_sid = init.get("session_id")
        if init.get("apiKeySource") not in (None, "none"):
            return {"arm": label, "run": run, "error": f"not subscription: {init.get('apiKeySource')}"}
        body, tools, mid = first_turn(events)
        if mid is None:
            return {"arm": label, "run": run,
                    "error": f"no assistant turn (exit {p.returncode}): {p.stderr.strip()[-200:]}"}
        return {"arm": label, "run": run, "route": "fork", "model": init.get("model"),
                "tools": tools, "text": body}
    except subprocess.TimeoutExpired:
        return {"arm": label, "run": run, "error": f"timeout after {timeout}s"}
    finally:
        # Delete ONLY this fork's two files, named by id: other sessions write new
        # transcripts into the same directory.
        seed_path.unlink(missing_ok=True)
        if fork_sid and fork_sid != sid:
            f = projdir / f"{fork_sid}.jsonl"
            if keep and f.exists():
                shutil.move(str(f), str(pathlib.Path(keep) / f.name))
            else:
                f.unlink(missing_ok=True)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--transcript", required=True)
    ap.add_argument("--cut", type=int, required=True,
                    help="index of the LAST record kept: the tool_result the turn answered")
    ap.add_argument("--arms", required=True, help="comma-separated; prefix s for stripped (s0, s1b)")
    ap.add_argument("--runs", type=int, default=10)
    ap.add_argument("--pool", type=int, default=2)
    ap.add_argument("--timeout", type=int, default=900)
    ap.add_argument("--workdir", required=True, help="scratch dir for the shadow files")
    ap.add_argument("--keep", help="move each fork's transcript here, for inspection")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    src = [json.loads(l) for l in open(args.transcript)][:args.cut + 2]
    nxt = src[args.cut + 1]
    rendered = nxt.get("rendered") or []
    if nxt.get("type") != "attachment" or not rendered:
        sys.exit(f"record {args.cut + 1} is not a rendered attachment; no faithful prompt")
    prompt = "\n".join(c["content"] for c in rendered)
    projdir = pathlib.Path(args.transcript).parent
    cfg = json.load(open(PROFILE / ".claude.json"))["mcpServers"]
    mcp = json.dumps({"mcpServers": {k: cfg[k] for k in ("codescout", "researcher") if k in cfg}})
    base = pathlib.Path(args.workdir)
    shadows: dict[str, Shadow] = {}

    jobs = []
    for a in args.arms.split(","):
        stripped, arm = (True, a[1:]) if a.startswith("s") else (False, a)
        if arm != "0" and arm not in ARMS:
            sys.exit(f"arm {arm!r} is not registered in phase2-replay.ARMS")
        v = "stripped" if stripped else "full"
        shadows.setdefault(v, Shadow(base, v, src[:args.cut + 1]))
        jobs += [(arm, shadows[v], r) for r in range(args.runs)]
    print(f"fork route: {len(jobs)} forks, model {MODEL}, cut after record {args.cut}")
    with ThreadPoolExecutor(max_workers=args.pool) as ex, open(args.out, "a") as out:
        futs = [ex.submit(fork, src, args.cut, prompt, projdir, s, mcp, a, r, args.timeout, args.keep)
                for a, s, r in jobs]
        for f in futs:
            row = f.result()
            out.write(json.dumps(row) + "\n")
            out.flush()
            print(row["arm"], row["run"], row.get("error") or f"tools={row['tools']}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
